services:
  - type: web
    name: formexa-dslap
    env: node
    plan: free
    buildCommand: npm install && node build.js
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
