services:
  - type: web
    name: formexa-dslap
    env: node
    plan: free
    buildCommand: npm install && node build.js
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

  - type: static
    name: formexa-dslap-static
    buildCommand: npm install && node build.js
    staticPublishPath: ./dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
